version: "3.8"

services:
  web:
    build: .
    container_name: digitalizador_web
    restart: always
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - web_static:/app/staticfiles
      - web_media:/app/media
    networks:
      - default
      - web
    env_file:
      - stack.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.digitalizador.rule=Host(`digitalizadordeideias.com.br`)"
      - "traefik.http.routers.digitalizador.entrypoints=websecure"
      - "traefik.http.routers.digitalizador.tls=true"
      - "traefik.http.routers.digitalizador.tls.certresolver=myresolver"
      - "traefik.http.services.digitalizador.loadbalancer.server.port=8000"

  db:
    image: postgres:15
    container_name: digitalizador_db
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    # AQUI ESTAVA O ERRO. AGORA VAMOS MAPEAS AS VARI√ÅVEIS:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - default

volumes:
  postgres_data_prod:
  web_static:
  web_media:

networks:
  default:
  web:
    external: true
